<?php
    $lang['number']   = 'Ma don hang';
    $lang['date']     = 'Ngay lap hoa don';
    $lang['time']     = 'Thoi gian lap';
    $lang['due']      = 'Ngay het han';
    $lang['to']       = 'Hoa don den';
    $lang['from']     = 'Hoa don tu';
    $lang['product']  = 'Ten san pham';
    $lang['qty']      = 'So luong';
    $lang['price']    = 'Gia';
    $lang['discount'] = 'Giam gia';
    $lang['vat']      = 'Phi van chuyen';
    $lang['total']    = 'Tong tien';
    $lang['page']     = 'Trang';
    $lang['page_of']  = 'trong so';
